name = "devOS Season Aero"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce5f9e581e5246a61b8c4526ceaab4c4ef550fa45aac3d953bcd2519ce115e15"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
unsup = "1.1.6"
