name = "devOS Season Aero"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e7db4bbfd9904373d638845c893e3a67b910eb125b8495d17ecb4de9d121d42"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
unsup = "1.1.6"
