name = "devOS Season Aero"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c4eb3b2bbb0e7cc7cd4fdf953c9e9ad7fa7d726efe10f96fa0736dbb2697f61"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
unsup = "1.1.6"
